<div class="header-sister-site">
	<div class="site_logos d-container">
		<ul>
			<? if(1 == 0): ?>
			<li class="site_logo"><a href="http://www.bforbooks.com.au/"><span class="s_logo bforbooks"><span></span></span></a></li>
			<li class="site_logo"><a href="http://www.cosynest.com.au/"><span class="s_logo cosynest"><span></span></span></a></li>			
			<li class="site_logo"><span class="s_logo kiddiespace"><span></span></span></li>
			<li class="site_logo"><a href="http://www.yogee.com.au/"><span class="s_logo yogee"><span></span></span></a></li>
			<? endif;?>
			<li class="site_logo active"><span class="s_logo nextoner"><span></span></span></li>
		</ul>
	</div>
</div>